services:
  php_container:
    container_name: php_container
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    command: "php -S 0.0.0.0:8000 -t ./"
    ports:
      - 8000:8000
    tty: true

  postgres:
    container_name: postgres
    image: postgres:16.4
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mailing_db
      PGDATA: /data/postgres
    volumes:
      - ./postgres_data:/data/postgres
    ports:
      - 5432:5432

  dbgate:
    container_name: dbgate
    image: dbgate/dbgate:5.5.6-alpine
    restart: always
    ports:
      - 8087:3000
    volumes:
      - ./postgres_data:/data/postgres
    environment:
      CONNECTIONS: con1,con2,con3,con4

      LABEL_con1: MySql
      SERVER_con1: mysql
      USER_con1: root
      PASSWORD_con1: TEST
      PORT_con1: 3306
      ENGINE_con1: mysql@dbgate-plugin-mysql

      LABEL_con2: Postgres
      SERVER_con2: postgres
      USER_con2: root
      PASSWORD_con2: password
      PORT_con2: 5432
      ENGINE_con2: postgres@dbgate-plugin-postgres

      LABEL_con3: MongoDB
      URL_con3: mongodb://mongo:27017
      ENGINE_con3: mongo@dbgate-plugin-mongo

      LABEL_con4: SQLite
      FILE_con4: /home/jan/feeds.sqlite
      ENGINE_con4: sqlite@dbgate-