version: '3'

networks:
    mysql_8_adminer:

services:

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: mysqlDB
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        # restart: unless-stopped  
        environment:
            # MYSQL_USER: user # no need root by default
            MYSQL_ROOT_PASSWORD: password
            # MYSQL_PASSWORD: password
        networks:
            - mysql_8_adminer

    # adminer        
    adminer:
        image: adminer
        # restart: unless-stopped 
        ports:
            - 8085:8080
        networks:
            - mysql_8_adminer
