version: '3'

services:

  webserver:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx_web
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html

  php:
    build: ./docker/php/
    container_name: php_server
    expose:
      - 9000
    volumes:
      - ./src:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini


  # postgresql
  postgresql-service:
    image: postgres:14
    container_name: postgre_db
    ports:
      - 5432:5432
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    # restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  # adminer
  adminer:
    image: adminer:4.8.1
    # restart: unless-stopped
    ports:
      - 8085:8080

# it will persist data after $ docker-compose down
volumes:
  data: