version: '3'
services:
  mongo:
    image: mongo:4.4
    # restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express:1.0.0-20
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo

# for persist data after docker-compose down
volumes:
    data:  

