FROM node:16.0.0-alpine3.12

# install vim
RUN apk add vim
RUN echo set number >> /etc/vim/vimrc
RUN echo set tabstop=4  >> /etc/vim/vimrc
RUN echo colo ron  >> /etc/vim/vimrc
RUN echo set autoindent  >> /etc/vim/vimrc
